version: '3'

#networks:
#    mymulticont:
#        name: mymulticont

services:
  myredis:
    container_name: myredis
    image: 'redis:alpine'
    depends_on:
      - mypostgres
#        networks:
#            - mymulticont

  mypostgres:
    container_name: mypostgres
    image: 'postgres:alpine'
#        networks:
#            - mymulticont
    environment:
      POSTGRES_PASSWORD: 'Passw0rd'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'mypostgres'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  mybackend:
    container_name: mybackend
    restart: always
#        networks:
#            - mymulticont
    build:
      dockerfile: Dockerfile
      context: ./mybackend
    volumes:
      - /opt/myapp/node_modules
      - ./mybackend:/opt/myapp
    environment:
      POSTGRES_PASSWORD: 'Passw0rd'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'mypostgres'
      POSTGRES_PORT: 5432
      REDIS_HOST: 'myredis'
      REDIS_PORT: 6379
    ports:
      - 4000:4000
    depends_on:
      - mypostgres
      - myredis
  
  mynginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./mynginx
    ports: 
      - "9090:80"
  
  myfrontend:
    container_name: myfrontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./myfrontend
    volumes:
      - /opt/app/
      - ./myfrontend:/opt/app
    ports:
      - 3000:3000
    depends_on:
      - mybackend
